#for documentation see project at https://github.com/Dilbert66/esphome-dsckeybus
substitutions:
  name: "dscalarm" #unique network name
  friendlyName: "DSC Alarm" #friendly name for this device
  panelId: DSCAlarm  #used as the service variable name.
  
dsc_alarm_panel:
  id: $panelId
  #you can enter a list of user codes mapped to their names for display in armed/disarmed event messages
  usercodes: "1:John,2:Sally,3:Bob" #
  
  #Only comes into effect if a password prompt occurs when arming eg. night mode
  accesscode: !secret access_code 
  
  #used to select the default partition associated with the alarm panel messages
  defaultpartition: "1" 
  
  maxzones: "32" # maximum amount of zones your system supports
  
  # dsc debug level: 0 = off, 1 = minimal, 2 = all packets shown on console  3 =  + serial port debugging
  dscdebuglevel: "2"  
   
  #virtual zone expander addresses:
  # 9  - zones 9-16
  # 10 - zones 17-24
  # 11 - zones 25-32
  # 12 - zones 33-40 (for systems with 64 zone support)
  # 13 - zones 41-48 (for systems with 64 zone support)
  # 14 - zones 49-56 (for systems with 64 zone support)
  # 16 - zones 57-64 (for systems with 64 zone support) 
  # !! Note: if you already have real zone expanders on the bus (pc5108), ensure you do use the same addresses here. 
  expanderaddr1: "0" # 1st zone expander emulator address to use . Set to 0 to disable. 
  expanderaddr2: "0" # 2nd expander emulator address to use . Set to 0 to disable. 

  ##ESP32 Pins
  dscclockpin: "22"
  dscreadpin: "21"
  dscwritepin: "18"
  
  ##WT32-ETH01 Pins
  #dscclockpin: "15"
  #dscreadpin: "14"
  #dscwritepin: "4"
  
  ##ESP8266 Pins
  #dscclockpin: "5"
  #dscreadpin: "4"
  #dscwritepin: "15" 

  #periodic check for trouble messages in seconds. Minium 30s. Defaults to 120s (2 minutes)
  trouble_fetch_update_time: 120

  #flag to have the esp check for trouble statuses for devices/zones when the trouble light goes on or off
  #Note: It will prevent the physical panel from beeping to let you know as the check resets the beep.
  #Sends *21 and *27 to the panel. Default: true
  trouble_fetch: true
  
  #if true the available states will be:
  #triggered,armed_home,armed_away,armed_night,pending,arming,disarmed,ready,not_ready
  #if false the states will be:
  #triggered,armed_home,armed_away,armed_night,pending,arming,disarmed
  #the default is "false"
  detailed_partition_state: false
 
  clean_build: "false" #default is false.  set to true if getting duplication errors in linking step.  

esp32: 
  board: nodemcu-32s
  #board: esp-wrover-kit # use with WT32-ETH01
  framework: 
    type: arduino
    version: recommended

#esp8266:    
  #board: nodemcuv2
  #framework:
    #version: recommended 

#location of alarm panel code.  You can use the github release version  or 
#copy the code to directory "my_components" in your main esphome directory   
# see here for more info: https://esphome.io/components/external_components       
external_components:
  - source: github://Dilbert66/esphome-components@dev #uncomment to use github repository (dev branch selected)
  #- source:  my_components #uncomment to use local directory 
    components: [dsc_alarm_panel,web_keypad,mg_lib] 
    refresh: 10min
    
    
# web keypad component. Remove or comment if not needed
# each included files will be downloaded automatically and compiled within the flash.  
# there will be no need for internet access when running.
# For www.js build details and source: https://github.com/Dilbert66/esphome-webserver-custom/tree/keypad
# Component source: https://github.com/Dilbert66/esphome-components/tree/keypad/components/web_keypad
### Note: this is an ESP32 only component. The esp8266 does not support the resources needed.


web_keypad:
  port: 80 
  partitions: 1  # a keypad will be shown for each partition
  log: false
  auth:          #this section is optional. Enable if you need authentication/encryption
    username: test
    password: test
    encryption: true  #set true to use AES256HMAC encryption/auth for sent keys and returned LCD messages
                      #set to false to use Digest authentication - no encryption
  config_url: https://dilbert66.github.io/config_files/config_dsc.yml  
  js_url: https://dilbert66.github.io/js_files/www.js
  ## If you prefer to use locally hosted compile time files comment the two lines above and uncomment below
  #config_local: ./config_dsc.yml    
  #js_local: ./www.js    
  
  ## custom function call to send keypresses if other than dsc/vista components are used. Parmeters are a string keys and int partition
  #service_lambda: |- 
      #$panelId->alarm_keypress_partition(keys,partition);      

  
esphome:
  name: $name
  friendly_name: $friendlyName
  
#Example of how to set the panel time from the esp time on bootup  
  #on_boot:
    #priority: 600
    #then:
      #- lambda: |-
         #   $panelId->set_panel_time();    

#output sympols to output.map for debugging. You can remove if not needed
  platformio_options:
    build_flags: 
        - "-Wl,-Map,output.map"  

#you can remove/disable this section if you don't want your panel time updated automatically. 
#interval:
  #- interval: 7200s
   # then:
    #  - lambda: |-
     #     $panelId->set_panel_time();  
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "$name"
    password: !secret wifi_password

# Configuration for WT32-ETH01. Also comment out wifi section
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO16

logger:
  baud_rate: 115200
  level: DEBUG

api:
   encryption:
    key: !secret encryption_key
    
    
#to use mqtt disable the api: section above. This enables you to use esphome with 
#non homeassistant systems
#modify the mqtt section to your needs
#See: https://esphome.io/components/mqtt.html

#mqtt:
  #broker: 192.168.2.175
  #port: 1883
  #username: mqttuser
  #password: mqttuser
  #discovery_prefix: "homeassistant"
  #topic_prefix: $name
 
safe_mode: 

ota:
   password: !secret ota_password
   platform: esphome
   on_begin: 
       switch.turn_off: connection_status_switch   
   
time:
 - platform: sntp


################################################################################
# Edit binary and text sensors below to suit your alarm setup. 
# The id code is entered using the "id:" tag.  Alternatively you can
# add the id code in round brackets  at the end of the sensor name: eg. (z1)
# You can safely add or remove any sensors as needed.

binary_sensor:
### zone setup ###
# zone status open/close for each zone 
# zone id code = z+zone number  
  - platform: dsc_alarm_panel
    id: z1
    name: "Front door z1"
    device_class: door

  - platform: dsc_alarm_panel
    id: z2
    name: "Garage door z2"
    device_class: door
      

  - platform: dsc_alarm_panel
    id: z3  
    name: "Back door z3"
    device_class: door

  - platform: dsc_alarm_panel
    id: z4  
    name: "Living room window z4"
    device_class: window
   
  - platform: dsc_alarm_panel
    id: z5
    name: "Dining room window z5"
    device_class: window
      
  - platform: dsc_alarm_panel
    id: z6
    name: "Family room window LF z6"
    device_class: window
      
  - platform: dsc_alarm_panel
    id: z7  
    name: "Family room window RF z7"
    device_class: window
      
  - platform: dsc_alarm_panel
    id: z8  
    name: "Basement windows z8"
    device_class: window
     
  - platform: dsc_alarm_panel
    id: z9
    name: "Upstairs motion z9"
    device_class: motion
     
  - platform: dsc_alarm_panel
    id: z10  
    name: "Basement motion z10"
    device_class: motion
     
  - platform: dsc_alarm_panel
    id: z11  
    name: "Main floor motion z11"
    device_class: motion
     
  - platform: dsc_alarm_panel
    id: z17  
    name: "Top floor motion z17"
    device_class: motion    
   
### non zone sensors ###
# partition ready indicators
# ready id code = rdy_ + partition number
  - platform: dsc_alarm_panel
    id: rdy_1  
    name: "Ready partition 1"
     
  - platform: dsc_alarm_panel
    id: rdy_2  
    name: "Ready partition 2"    
     
# partition arm indicators
# arm id code = arm_ + partition number
  - platform: dsc_alarm_panel
    id: arm_1  
    name: "Armed partition 1"
     
  - platform: dsc_alarm_panel
    id: arm_2  
    name: "Armed partition 2"   
      
# panel trouble status indicator
# trouble id code = tr
  - platform: dsc_alarm_panel
    id: tr  
    name: "Trouble Status"
    device_class: problem
     
# bat id code = bat
# panel battery status indicator
  - platform: dsc_alarm_panel
    id: bat  
    name: "Battery Status"
    device_class: problem
     
# ac id code = ac
# panel AC power indicator
  - platform: dsc_alarm_panel
    id: ac  
    name: "AC Status"
    device_class: plug
     
# partition fire alarm indicators
# fire id code = fa_ + partition number  
  - platform: dsc_alarm_panel
    id: fa_1  
    device_class: smoke
    name: "Fire Status partition 1"
       
  - platform: dsc_alarm_panel
    id: fa_2  
    device_class: smoke
    name: "Fire Status partition 2"  

# partition in alarm indicators
# alarm id code = al_ + partition number  
  - platform: dsc_alarm_panel
    id: al_1  
    name: "Alarm Status partition 1"
     
  - platform: dsc_alarm_panel
    id: al_2  
    name: "Alarm Status partition 2"  
     
# relay PGM channels. Will show the state of the activate relay channel on/off
# relay id code = r + channel number
  - platform: dsc_alarm_panel
    id: r1  
    name: "PGM 1"

  - platform: dsc_alarm_panel
    id: r2  
    name: "PGM 2"
     
  - platform: dsc_alarm_panel
    id: r3  
    name: "PGM 3"
     
  - platform: dsc_alarm_panel
    id: r4  
    name: "PGM 4"

  #- platform: dsc_alarm_panel
  #  name: "PGM 5"

  #- platform: dsc_alarm_panel
  #  name: "PGM 6"

  #- platform: dsc_alarm_panel
  #  name: "PGM 7"

  #- platform: dsc_alarm_panel
  #  name: "PGM 8"
              
text_sensor:
# general system status online/disconnected 
# system status id code = ss
  - platform: dsc_alarm_panel
    id: ss  
    name: "System Status"
    icon: "mdi:shield"

# battery level status for wireless channels, tamper , in alarm, etc for individual zones
# zone status id code = zs    
  - platform: dsc_alarm_panel
    id: zs  
    name: "Zone Status"
    icon: "mdi:shield"  

# partition status ie ready/not ready, triggered, etc
# partition status id code = ps_ + partition number   
  - platform: dsc_alarm_panel
    id: ps_1  
    name: "Status partition 1"
    icon: "mdi:shield"

  - platform: dsc_alarm_panel
    id: ps_2  
    name: "Status partition 2" 
    icon: "mdi:shield"  

# more verbose message regarding the partition status. ie zones open, bypassed, etc
# partition message id code = msg_ + partition number    
  - platform: dsc_alarm_panel
    id: msg_1  
    name: "Msg partition 1"
    icon: "mdi:alert-box"

  - platform: dsc_alarm_panel
    id: msg_2  
    name: "Msg partition 2"
    icon: "mdi:alert-box"

# virtual lcd keypad line1 and line2 messages for each partition   
# partition line1 id code = ln1_ + partition number
# partition line2 id code = ln2_ + partition number
# partition 1
  - platform: dsc_alarm_panel
    id: ln1_1  
    name: "line1 partition 1"
    icon: "mdi:alert-box"

  - platform: dsc_alarm_panel
    id: ln2_1  
    name: "line2 partition 1"
    icon: "mdi:alert-box"  

# partition 2
  - platform: dsc_alarm_panel
    id: ln1_2  
    name: "line1 partition 2"
    icon: "mdi:alert-box"

  - platform: dsc_alarm_panel
    id: ln2_2  
    name: "line2 partition 2"
    icon: "mdi:alert-box" 

# generic event messages from panel
# panel event id code = evt
  - platform: dsc_alarm_panel
    id: evt  
    name: "event"
    icon: "mdi:alert-box" 
  
# partition beeps
# beeps id code = bp_ + partition number
  - platform: dsc_alarm_panel
    id: bp_1  
    name: "beeps partition 1"
    icon: "mdi:alert-box" 

  - platform: dsc_alarm_panel
    id: bp_2  
    name: "beeps partition 2"
    icon: "mdi:alert-box"   

 # panel trouble messages  
 # panel msg id code = tr_msg
  - platform: dsc_alarm_panel
    id: tr_msg  
    name: "Trouble Msg" 
    icon: "mdi:alert-box"

# name of the zone that triggered the last alarm
# zone alarm id code = (za_ + partition number)
  - platform: dsc_alarm_panel
    id: za_1
    name: zone alarm (za_1)
    icon: "mdi:alert-box" 

# name or id of the user that last armed/disarmed the partition
# user id code = (user_ + partition number)
  - platform: dsc_alarm_panel
    id: user_1
    name: Arming/Disarming user (user_1)
    icon: "mdi:alert-box" 


 #optional. Example button config to send a keypad cmd. This one sends a PGM1 relay on cmd on partition 1
button:
    - platform: template
      name: Gate Button
      id: gate1
      icon: "mdi:emoticon-outline"    
      on_press:
        - lambda: |-
            $panelId->alarm_keypress_partition("*71",1);   

# this sensor below is optional - example use of pin d8 as a zone trigger pin for the emulated zone expander  
# this emulates the hardware connection for a pc5108 board. Use a pull down/pull up resistor.  Adjust logic accordingly for the correct logic output. ie invert
 # - platform: gpio  
 #   pin: D8
 #   device_class: window
 #   on_press:       #pin high=on(open), pin low=off(closed)
 #     - lambda: |-
 #         $panelId->setZoneFault(17,1);  #set zone 17 as open
 #   on_release:
 #     - lambda: |-
 #         $panelId->setZoneFault(17,0);  #set zone 17 as closed
 


 # end of panel sensor setup - no need to edit anything below.
##########################################################################################
switch:
    #shows status of connection status to panel.  You can disconnect before upload using the switch.
  - platform: template
    name: "Connection"
    id: connection_status_switch
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return dsc.keybusConnected;
    icon: "mdi:shield-link-variant"
    turn_on_action:
      - switch.toggle: restart_switch
    turn_off_action:
      - lambda: |-
          disconnectKeybus();

  - platform: restart
    id: restart_switch
    
  - platform: safe_mode
    name: "Safe Mode" 



